# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Md < Formula
  desc "Markdown cli that enables efficiently exploring markdown content and extractin"
  homepage "https://github.com/kym6464/md"
  url "https://github.com/kym6464/md/archive/refs/tags/v1.0.9.tar.gz"
  version "1.0.9"
  sha256 "de2679f15074b0909c425e1866040bd56fb9f209c44b375df48c3eb523a7a590"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kym6464/md/releases/download/v1.0.9/md-1.0.9-darwin-amd64.tar.gz"
      sha256 "4d2416a3c29dbe785d71938877d314909ed38025d5ffe55c1fb408f36f1f4e23"
    end

    on_arm do
      url "https://github.com/kym6464/md/releases/download/v1.0.9/md-1.0.9-darwin-arm64.tar.gz"
      sha256 "5e9fbd455d8064a9aea5b4aef7a81f4ac08141709a7f8725b378354c97816fc1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kym6464/md/releases/download/v1.0.9/md-1.0.9-linux-amd64.tar.gz"
      sha256 "522a693301343ad78ae1da6d85a925805b64a577cd750fbae42d7e2766179dc2"
    end

    on_arm do
      url "https://github.com/kym6464/md/releases/download/v1.0.9/md-1.0.9-linux-arm64.tar.gz"
      sha256 "c7dddbf2595b26cac45935cb7856d87246ca77b29f260642450369d1323f5c2a"
    end
  end

  def install
    bin.install "md"
  end
end
