# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Md < Formula
  desc "Markdown cli that enables efficiently exploring markdown content and extractin"
  homepage "https://github.com/kym6464/md"
  url "https://github.com/kym6464/md/archive/refs/tags/v1.0.6.tar.gz"
  sha256 "56897e14b89668ae7dd827b5a9d76a42fdb0f9375741dcf64360a8b5d1d3a531"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kym6464/md/releases/download/v1.0.6/md-1.0.6-darwin-amd64.tar.gz"
      sha256 "fb72bed7acfc0a0d716a6f80dbea6ac554fb9cc0113ebb731894b30b4363f2c6"
    end

    on_arm do
      url "https://github.com/kym6464/md/releases/download/v1.0.6/md-1.0.6-darwin-arm64.tar.gz"
      sha256 "9d42b045d3fc1abe0a9b5d0b8c631b5470932d44bbc831cf3c6a22136932bfc7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kym6464/md/releases/download/v1.0.6/md-1.0.6-linux-amd64.tar.gz"
      sha256 "ebd336249a84abe3583af279fc1c01a3f509d630868ea5108ff6110cdb3d0ec0"
    end

    on_arm do
      url "https://github.com/kym6464/md/releases/download/v1.0.6/md-1.0.6-linux-arm64.tar.gz"
      sha256 "1fb3e60998f54f07059975b45f6bc1470c47a156a818e56a7beb07f66454f67a"
    end
  end

  def install
    bin.install "md"
  end
end
